import {
  Profile,
  Household,
  HouseholdMember,
  Person,
  Category,
  Card,
  Expense,
  Statement,
  Installment,
  Reimbursement,
  RecurringExpense,
  Notification,
  AuditLog,
} from './types';

// INITIAL DEMO SEED DATA (Section 30 compliance)
export const DEMO_PROFILES: Profile[] = [
  {
    id: 'user-cesar-111',
    email: 'cesar@hogar.com',
    full_name: 'César Rodríguez',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-antonela-222',
    email: 'antonela@hogar.com',
    full_name: 'Antonela Gómez',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const DEMO_HOUSEHOLD: Household = {
  id: 'household-hogar-999',
  name: 'Hogar César y Antonela',
  created_by: 'user-cesar-111',
  created_at: '2026-01-01T00:00:00Z',
};

export const DEMO_MEMBERS: HouseholdMember[] = [
  {
    id: 'member-1',
    household_id: 'household-hogar-999',
    user_id: 'user-cesar-111',
    role: 'admin',
    joined_at: '2026-01-01T00:00:00Z',
    profile: DEMO_PROFILES[0],
  },
  {
    id: 'member-2',
    household_id: 'household-hogar-999',
    user_id: 'user-antonela-222',
    role: 'member',
    joined_at: '2026-01-02T00:00:00Z',
    profile: DEMO_PROFILES[1],
  },
];

export const DEMO_PEOPLE: Person[] = [
  {
    id: 'person-cesar',
    household_id: 'household-hogar-999',
    user_id: 'user-cesar-111',
    name: 'César',
    last_name: 'Rodríguez',
    alias: 'César (Titular)',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'person-antonela',
    household_id: 'household-hogar-999',
    user_id: 'user-antonela-222',
    name: 'Antonela',
    last_name: 'Gómez',
    alias: 'Anto',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'person-marcos-tercero',
    household_id: 'household-hogar-999',
    user_id: null,
    name: 'Marcos',
    last_name: 'Pérez',
    alias: 'Amigo Marcos',
    phone: '+5493512345678',
    notes: 'Compañero de trabajo de César',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-10T00:00:00Z',
  },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-super', household_id: null, name: 'Supermercado', color: '#16a34a', icon: 'shopping-cart', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-comida', household_id: null, name: 'Comida', color: '#ea580c', icon: 'utensils', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-salidas', household_id: null, name: 'Salidas', color: '#d97706', icon: 'coffee', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-combustible', household_id: null, name: 'Combustible', color: '#dc2626', icon: 'fuel', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-hogar', household_id: null, name: 'Hogar', color: '#0284c7', icon: 'home', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-servicios', household_id: null, name: 'Servicios', color: '#4f46e5', icon: 'zap', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-suscripciones', household_id: null, name: 'Suscripciones', color: '#9333ea', icon: 'tv', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-tecnologia', household_id: null, name: 'Tecnología', color: '#6366f1', icon: 'laptop', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-ropa', household_id: null, name: 'Ropa', color: '#db2777', icon: 'shirt', is_active: true, is_default: true, created_at: '2026-01-01' },
  { id: 'cat-otros', household_id: null, name: 'Otros', color: '#64748b', icon: 'more-horizontal', is_active: true, is_default: true, created_at: '2026-01-01' },
];

export const DEMO_CARDS: Card[] = [
  {
    id: 'card-visa-galicia',
    household_id: 'household-hogar-999',
    name: 'Visa Galicia César',
    bank: 'Banco Galicia',
    cardholder_name: 'César Rodríguez',
    brand: 'Visa',
    last_four_digits: '4589',
    default_closing_day: 25,
    default_due_day: 5,
    primary_currency: 'ARS',
    color: '#0284c7',
    icon: 'credit-card',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'card-master-santafe',
    household_id: 'household-hogar-999',
    name: 'Mastercard Santa Fe Antonela',
    bank: 'Banco Santa Fe',
    cardholder_name: 'Antonela Gómez',
    brand: 'Mastercard',
    last_four_digits: '8912',
    default_closing_day: 20,
    default_due_day: 2,
    primary_currency: 'ARS',
    color: '#e11d48',
    icon: 'credit-card',
    is_active: true,
    created_by: 'user-antonela-222',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'card-visa-nacion',
    household_id: 'household-hogar-999',
    name: 'Visa Banco Nación',
    bank: 'Banco Nación',
    cardholder_name: 'César Rodríguez',
    brand: 'Visa',
    last_four_digits: '1044',
    default_closing_day: 28,
    default_due_day: 8,
    primary_currency: 'USD',
    color: '#16a34a',
    icon: 'credit-card',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const DEMO_EXPENSES: Expense[] = [
  // 1. Gasto 50/50 compartido
  {
    id: 'exp-supermercado-1',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    category_id: 'cat-super',
    purchaser_id: 'person-cesar',
    description: 'Supermercado semanal Coto',
    merchant: 'Coto CICA',
    total_amount: 80000,
    currency: 'ARS',
    purchase_date: '2026-07-15',
    installments_count: 1,
    distribution_type: 'shared_equal',
    notes: 'Compra para la semana',
    created_by: 'user-cesar-111',
    created_at: '2026-07-15T14:30:00Z',
    updated_at: '2026-07-15T14:30:00Z',
    allocations: [
      { id: 'alloc-1a', expense_id: 'exp-supermercado-1', person_id: 'person-cesar', percentage: 50, amount: 40000 },
      { id: 'alloc-1b', expense_id: 'exp-supermercado-1', person_id: 'person-antonela', percentage: 50, amount: 40000 },
    ],
  },
  // 2. Compra en 6 cuotas
  {
    id: 'exp-tv-cuotas',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    category_id: 'cat-tecnologia',
    purchaser_id: 'person-cesar',
    description: 'Smart TV 55" para el living',
    merchant: 'Mercado Libre',
    total_amount: 450000,
    currency: 'ARS',
    purchase_date: '2026-06-10',
    installments_count: 6,
    distribution_type: 'shared_equal',
    notes: 'Compra en 6 cuotas sin interés',
    created_by: 'user-cesar-111',
    created_at: '2026-06-10T11:00:00Z',
    updated_at: '2026-06-10T11:00:00Z',
    allocations: [
      { id: 'alloc-2a', expense_id: 'exp-tv-cuotas', person_id: 'person-cesar', percentage: 50, amount: 225000 },
      { id: 'alloc-2b', expense_id: 'exp-tv-cuotas', person_id: 'person-antonela', percentage: 50, amount: 225000 },
    ],
  },
  // 3. Gasto 100% de tercero (Marcos amigazo)
  {
    id: 'exp-tercero-marcos',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    category_id: 'cat-ropa',
    purchaser_id: 'person-cesar',
    description: 'Zapatillas Nike para Marcos',
    merchant: 'Dexter Deportes',
    total_amount: 95000,
    currency: 'ARS',
    purchase_date: '2026-07-22',
    installments_count: 1,
    distribution_type: 'third_party_100',
    notes: 'Se las compré con descuento, me devuelve el dinero',
    created_by: 'user-cesar-111',
    created_at: '2026-07-22T18:20:00Z',
    updated_at: '2026-07-22T18:20:00Z',
    allocations: [
      { id: 'alloc-3', expense_id: 'exp-tercero-marcos', person_id: 'person-marcos-tercero', percentage: 100, amount: 95000 },
    ],
  },
  // 4. Gasto en USD
  {
    id: 'exp-usd-hosting',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-nacion',
    category_id: 'cat-servicios',
    purchaser_id: 'person-cesar',
    description: 'Servidores AWS & Vercel',
    merchant: 'Vercel Inc',
    total_amount: 120,
    currency: 'USD',
    purchase_date: '2026-07-05',
    installments_count: 1,
    distribution_type: 'own',
    notes: 'Proyecto laboral propio',
    created_by: 'user-cesar-111',
    created_at: '2026-07-05T09:00:00Z',
    updated_at: '2026-07-05T09:00:00Z',
    allocations: [
      { id: 'alloc-4', expense_id: 'exp-usd-hosting', person_id: 'person-cesar', percentage: 100, amount: 120 },
    ],
  },
];

export const DEMO_STATEMENTS: Statement[] = [
  {
    id: 'stmt-july-paid',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    period_year: 2026,
    period_month: 7,
    closing_date: '2026-07-25',
    due_date: '2026-08-05',
    status: 'paid',
    paid_at: '2026-08-03T10:00:00Z',
    paid_by_user_id: 'user-cesar-111',
    note: 'Pagado por débito automático Galicia',
    created_at: '2026-07-25T23:59:59Z',
    total_ars: 255000,
    total_usd: 0,
    installments_count: 3,
  },
  {
    id: 'stmt-aug-pending',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    period_year: 2026,
    period_month: 8,
    closing_date: '2026-08-25',
    due_date: '2026-09-05',
    status: 'open',
    created_at: '2026-07-26T00:00:00Z',
    total_ars: 170000,
    total_usd: 0,
    installments_count: 2,
  },
];

export const DEMO_REIMBURSEMENTS: Reimbursement[] = [
  {
    id: 'reimb-marcos-pending',
    household_id: 'household-hogar-999',
    expense_id: 'exp-tercero-marcos',
    debtor_person_id: 'person-marcos-tercero',
    creditor_person_id: 'person-cesar',
    amount: 95000,
    currency: 'ARS',
    status: 'pending',
    created_at: '2026-07-22T18:20:00Z',
  },
  {
    id: 'reimb-anto-received',
    household_id: 'household-hogar-999',
    expense_id: 'exp-supermercado-1',
    debtor_person_id: 'person-antonela',
    creditor_person_id: 'person-cesar',
    amount: 40000,
    currency: 'ARS',
    status: 'received',
    received_at: '2026-07-16T15:00:00Z',
    received_by_user_id: 'user-cesar-111',
    note: 'Transferencia por Mercado Pago recibida',
    created_at: '2026-07-15T14:30:00Z',
  },
];

export const DEMO_RECURRING: RecurringExpense[] = [
  {
    id: 'rec-netflix',
    household_id: 'household-hogar-999',
    card_id: 'card-master-santafe',
    category_id: 'cat-suscripciones',
    purchaser_id: 'person-antonela',
    description: 'Netflix Plan Familiar 4K',
    merchant: 'Netflix Argentina',
    amount: 14500,
    currency: 'ARS',
    distribution_type: 'shared_equal',
    frequency: 'monthly',
    start_date: '2026-01-01',
    next_execution_date: '2026-08-01',
    is_active: true,
    created_by: 'user-antonela-222',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rec-spotify',
    household_id: 'household-hogar-999',
    card_id: 'card-visa-galicia',
    category_id: 'cat-suscripciones',
    purchaser_id: 'person-cesar',
    description: 'Spotify Premium Duo',
    merchant: 'Spotify AB',
    amount: 4200,
    currency: 'ARS',
    distribution_type: 'shared_equal',
    frequency: 'monthly',
    start_date: '2026-01-01',
    next_execution_date: '2026-08-01',
    is_active: true,
    created_by: 'user-cesar-111',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    household_id: 'household-hogar-999',
    user_id: 'user-cesar-111',
    title: 'Próximo vencimiento de tarjeta',
    message: 'El resumen de Visa Galicia cierra el 25/08 y vence el 05/09.',
    type: 'warning',
    is_read: false,
    is_dismissed: false,
    created_at: '2026-07-30T09:00:00Z',
  },
  {
    id: 'notif-2',
    household_id: 'household-hogar-999',
    user_id: 'user-cesar-111',
    title: 'Devolución pendiente',
    message: 'Marcos tiene pendiente una devolución por $ 95.000,00.',
    type: 'info',
    is_read: false,
    is_dismissed: false,
    created_at: '2026-07-23T10:00:00Z',
  },
];
